set_project("saute_mouton")
set_version("0.1.0")
set_languages("c++23")

add_rules("mode.debug", "mode.release")
add_requires("libsdl2")
add_requires("nlohmann_json")

target("saute_mouton")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("src")
    add_packages("libsdl2")
    add_packages("nlohmann_json")
    add_defines("SDL_MAIN_HANDLED")
